name: Loki Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check docker-compose.yml
      run: |
        ls -la
        cat docker-compose.yml || echo "docker-compose.yml not found"

    - name: Build and start containers
      run: docker compose up -d

    - name: Check running containers
      run: docker ps -a

    - name: Create test log file
      run: |
        echo "Test log entry with Label browser" >> /tmp/webapp.log
        echo "File contents:"
        cat /tmp/webapp.log || echo "/tmp/webapp.log not found"

    - name: Update and restart containers
      run: |
        docker compose down
        docker compose up -d

    - name: Wait for containers to start
      run: |
        sleep 10
        docker ps -a

    - name: Check logs from Loki
      run: docker logs grafana-loki-2-1-loki-1 || echo "No logs from Loki"

    - name: Check logs from promtail
      run: docker logs grafana-loki-2-1-promtail-1 || echo "No logs from Promtail"

    - name: Check logs from grafana
      run: docker logs grafana-loki-2-1-grafana-1 || echo "No logs from Grafana"

    - name: Query Loki for logs
      run: |
        curl -G 'http://localhost:3100/loki/api/v1/query' \
          --data-urlencode 'query={job="webapp"}' || echo "Loki query failed"

    - name: Check Promtail positions file
      run: |
        cat /var/log/positions.yaml || echo "/var/log/positions.yaml not found"

    - name: List log files in /tmp
      run: |
        ls -la /tmp
        cat /tmp/webapp.log || echo "/tmp/webapp.log not found"

    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
        CYPRESS_GRAFANA_URL: http://localhost:9090
      with:
        working-directory: ./.github/tests

