name: Loki Task

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check docker-compose.yml
      run: ls -la

    - name: Build and start containers
      run: docker compose up -d

    - name: Check running containers
      run: docker ps -a

    - name: Create test log file
      run: echo "Test log entry" >> /tmp/webapp.log

    - name: Update and restart containers
      run: |
        docker compose down
        docker compose up -d

    - name: Wait for containers to start
      run: |
        sleep 10
        docker ps -a

    - name: Check logs from Loki
      run: |
        docker logs grafana-loki-2-1-loki-1 || echo "No logs from Loki"
        docker logs grafana-loki-2-1-promtail-1 || echo "No logs from Promtail"
        docker logs grafana-loki-2-1-grafana-1 || echo "No logs from Grafana"

    - name: Test containers functionality
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:8080
        CYPRESS_GRAFANA_URL: http://localhost:9090
      with:
        working-directory: ./.github/tests
